### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jigarmistry** [samdroid-apps/pyract#2]
How do I install this on mac ? Is there any installation steps ? 

Which libraries is it required for installation ? (libgirepository - how to install this on mac)
I really need to see this in action.

**Comment by samdroid-apps** [comment]
It uses the Gtk+ toolkit via python gobject introspection.  There seems to be a bug report about it on macports, but I have never used a mac so I can't help you very much:  https://trac.macports.org/ticket/40179

**Comment by samdroid-apps** [comment]
Closing as this I don't think this project is centered on Gtk+ Mac support.
